// Generated by tools/generate-v1p2-operation.mjs. Do not edit.

import type { Result } from "../../result.js";
import type { OneRosterV1p2PayloadDiagnostic } from "../model/json-value.js";
import {
  parseOneRosterV1p2CollectionAt,
  parseOneRosterV1p2SingletonAt,
  type OneRosterV1p2CollectionPayload,
  type OneRosterV1p2SingletonPayload,
} from "./payload-core.js";
import {
  parseOneRosterV1p2AcademicSession,
  type OneRosterV1p2AcademicSession,
} from "../model/rostering.js";
import {
  parseOneRosterV1p2AssessmentLineItem,
  type OneRosterV1p2AssessmentLineItem,
} from "../assessment-results/model.js";
import {
  parseOneRosterV1p2AssessmentResult,
  type OneRosterV1p2AssessmentResult,
} from "../assessment-results/model.js";
import { parseOneRosterV1p2Category, type OneRosterV1p2Category } from "../model/gradebook.js";
import { parseOneRosterV1p2Class, type OneRosterV1p2Class } from "../model/rostering.js";
import { parseOneRosterV1p2Course, type OneRosterV1p2Course } from "../model/rostering.js";
import {
  parseOneRosterV1p2Demographics,
  type OneRosterV1p2Demographics,
} from "../model/rostering.js";
import { parseOneRosterV1p2Enrollment, type OneRosterV1p2Enrollment } from "../model/rostering.js";
import { parseOneRosterV1p2LineItem, type OneRosterV1p2LineItem } from "../model/gradebook.js";
import { parseOneRosterV1p2Org, type OneRosterV1p2Org } from "../model/rostering.js";
import { parseOneRosterV1p2Resource, type OneRosterV1p2Resource } from "../model/resources.js";
import { parseOneRosterV1p2Result, type OneRosterV1p2Result } from "../model/gradebook.js";
import { parseOneRosterV1p2ScoreScale, type OneRosterV1p2ScoreScale } from "../model/gradebook.js";
import { parseOneRosterV1p2User, type OneRosterV1p2User } from "../model/rostering.js";

type Diagnostics = ReadonlyArray<OneRosterV1p2PayloadDiagnostic>;

/** Parse the generated academicSession collection response envelope. */
export function parseOneRosterV1p2AcademicSessionCollection(
  input: unknown,
  path = "$",
): Result<
  OneRosterV1p2CollectionPayload<OneRosterV1p2AcademicSession, "academicSessions">,
  Diagnostics
> {
  return parseOneRosterV1p2CollectionAt(
    input,
    path,
    "academicSessions",
    parseOneRosterV1p2AcademicSession,
  );
}

/** Parse the generated academicSession singleton response envelope. */
export function parseOneRosterV1p2AcademicSessionSingleton(
  input: unknown,
  path = "$",
): Result<
  OneRosterV1p2SingletonPayload<OneRosterV1p2AcademicSession, "academicSession">,
  Diagnostics
> {
  return parseOneRosterV1p2SingletonAt(
    input,
    path,
    "academicSession",
    parseOneRosterV1p2AcademicSession,
  );
}

/** Parse the generated assessmentLineItem collection response envelope. */
export function parseOneRosterV1p2AssessmentLineItemCollection(
  input: unknown,
  path = "$",
): Result<
  OneRosterV1p2CollectionPayload<OneRosterV1p2AssessmentLineItem, "assessmentLineItems">,
  Diagnostics
> {
  return parseOneRosterV1p2CollectionAt(
    input,
    path,
    "assessmentLineItems",
    parseOneRosterV1p2AssessmentLineItem,
  );
}

/** Parse the generated assessmentLineItem singleton response envelope. */
export function parseOneRosterV1p2AssessmentLineItemSingleton(
  input: unknown,
  path = "$",
): Result<
  OneRosterV1p2SingletonPayload<OneRosterV1p2AssessmentLineItem, "assessmentLineItem">,
  Diagnostics
> {
  return parseOneRosterV1p2SingletonAt(
    input,
    path,
    "assessmentLineItem",
    parseOneRosterV1p2AssessmentLineItem,
  );
}

/** Parse the generated assessmentResult collection response envelope. */
export function parseOneRosterV1p2AssessmentResultCollection(
  input: unknown,
  path = "$",
): Result<
  OneRosterV1p2CollectionPayload<OneRosterV1p2AssessmentResult, "assessmentResults">,
  Diagnostics
> {
  return parseOneRosterV1p2CollectionAt(
    input,
    path,
    "assessmentResults",
    parseOneRosterV1p2AssessmentResult,
  );
}

/** Parse the generated assessmentResult singleton response envelope. */
export function parseOneRosterV1p2AssessmentResultSingleton(
  input: unknown,
  path = "$",
): Result<
  OneRosterV1p2SingletonPayload<OneRosterV1p2AssessmentResult, "assessmentResult">,
  Diagnostics
> {
  return parseOneRosterV1p2SingletonAt(
    input,
    path,
    "assessmentResult",
    parseOneRosterV1p2AssessmentResult,
  );
}

/** Parse the generated category collection response envelope. */
export function parseOneRosterV1p2CategoryCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Category, "categories">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "categories", parseOneRosterV1p2Category);
}

/** Parse the generated category singleton response envelope. */
export function parseOneRosterV1p2CategorySingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Category, "category">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "category", parseOneRosterV1p2Category);
}

/** Parse the generated class collection response envelope. */
export function parseOneRosterV1p2ClassCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Class, "classes">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "classes", parseOneRosterV1p2Class);
}

/** Parse the generated class singleton response envelope. */
export function parseOneRosterV1p2ClassSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Class, "class">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "class", parseOneRosterV1p2Class);
}

/** Parse the generated course collection response envelope. */
export function parseOneRosterV1p2CourseCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Course, "courses">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "courses", parseOneRosterV1p2Course);
}

/** Parse the generated course singleton response envelope. */
export function parseOneRosterV1p2CourseSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Course, "course">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "course", parseOneRosterV1p2Course);
}

/** Parse the generated demographics collection response envelope. */
export function parseOneRosterV1p2DemographicsCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Demographics, "demographics">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(
    input,
    path,
    "demographics",
    parseOneRosterV1p2Demographics,
  );
}

/** Parse the generated demographics singleton response envelope. */
export function parseOneRosterV1p2DemographicsSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Demographics, "demographics">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "demographics", parseOneRosterV1p2Demographics);
}

/** Parse the generated enrollment collection response envelope. */
export function parseOneRosterV1p2EnrollmentCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Enrollment, "enrollments">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "enrollments", parseOneRosterV1p2Enrollment);
}

/** Parse the generated enrollment singleton response envelope. */
export function parseOneRosterV1p2EnrollmentSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Enrollment, "enrollment">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "enrollment", parseOneRosterV1p2Enrollment);
}

/** Parse the generated lineItem collection response envelope. */
export function parseOneRosterV1p2LineItemCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2LineItem, "lineItems">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "lineItems", parseOneRosterV1p2LineItem);
}

/** Parse the generated lineItem singleton response envelope. */
export function parseOneRosterV1p2LineItemSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2LineItem, "lineItem">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "lineItem", parseOneRosterV1p2LineItem);
}

/** Parse the generated org collection response envelope. */
export function parseOneRosterV1p2OrgCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Org, "orgs">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "orgs", parseOneRosterV1p2Org);
}

/** Parse the generated org singleton response envelope. */
export function parseOneRosterV1p2OrgSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Org, "org">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "org", parseOneRosterV1p2Org);
}

/** Parse the generated resource collection response envelope. */
export function parseOneRosterV1p2ResourceCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Resource, "resources">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "resources", parseOneRosterV1p2Resource);
}

/** Parse the generated resource singleton response envelope. */
export function parseOneRosterV1p2ResourceSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Resource, "resource">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "resource", parseOneRosterV1p2Resource);
}

/** Parse the generated result collection response envelope. */
export function parseOneRosterV1p2ResultCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2Result, "results">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "results", parseOneRosterV1p2Result);
}

/** Parse the generated result singleton response envelope. */
export function parseOneRosterV1p2ResultSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2Result, "result">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "result", parseOneRosterV1p2Result);
}

/** Parse the generated scoreScale collection response envelope. */
export function parseOneRosterV1p2ScoreScaleCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2ScoreScale, "scoreScales">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "scoreScales", parseOneRosterV1p2ScoreScale);
}

/** Parse the generated scoreScale singleton response envelope. */
export function parseOneRosterV1p2ScoreScaleSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2ScoreScale, "scoreScale">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "scoreScale", parseOneRosterV1p2ScoreScale);
}

/** Parse the generated user collection response envelope. */
export function parseOneRosterV1p2UserCollection(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2CollectionPayload<OneRosterV1p2User, "users">, Diagnostics> {
  return parseOneRosterV1p2CollectionAt(input, path, "users", parseOneRosterV1p2User);
}

/** Parse the generated user singleton response envelope. */
export function parseOneRosterV1p2UserSingleton(
  input: unknown,
  path = "$",
): Result<OneRosterV1p2SingletonPayload<OneRosterV1p2User, "user">, Diagnostics> {
  return parseOneRosterV1p2SingletonAt(input, path, "user", parseOneRosterV1p2User);
}

/** Runtime parser for one generated provider request payload codec. */
export type OneRosterV1p2GeneratedRequestPayloadParser = (
  input: unknown,
) => Result<unknown, Diagnostics>;

/** Request payload parsers projected from operation request-codec metadata. */
export const oneRosterV1p2GeneratedRequestPayloadParsers: Readonly<
  Record<string, OneRosterV1p2GeneratedRequestPayloadParser>
> = {
  lineItemCollection: parseOneRosterV1p2LineItemCollection,
  resultCollection: parseOneRosterV1p2ResultCollection,
  singleAssessmentLineItem: parseOneRosterV1p2AssessmentLineItemSingleton,
  singleAssessmentResult: parseOneRosterV1p2AssessmentResultSingleton,
  singleCategory: parseOneRosterV1p2CategorySingleton,
  singleLineItem: parseOneRosterV1p2LineItemSingleton,
  singleResult: parseOneRosterV1p2ResultSingleton,
  singleScoreScale: parseOneRosterV1p2ScoreScaleSingleton,
};

/** Runtime serializer for one generated operation's response envelope. */
export type OneRosterV1p2GeneratedResponseEnvelopeSerializer = (
  value: unknown,
) => Readonly<Record<string, unknown>>;

/** Exact operation-to-response-envelope serializers projected from OpenAPI payload metadata. */
export const oneRosterV1p2GeneratedResponseEnvelopeSerializers: Readonly<
  Record<string, OneRosterV1p2GeneratedResponseEnvelopeSerializer>
> = {
  getAllAcademicSessions: (value) => ({ academicSessions: value }),
  getAcademicSession: (value) => ({ academicSession: value }),
  getAllClasses: (value) => ({ classes: value }),
  getStudentsForClass: (value) => ({ users: value }),
  getTeachersForClass: (value) => ({ users: value }),
  getClass: (value) => ({ class: value }),
  getAllCourses: (value) => ({ courses: value }),
  getClassesForCourse: (value) => ({ classes: value }),
  getCourse: (value) => ({ course: value }),
  getAllDemographics: (value) => ({ demographics: value }),
  getDemographics: (value) => ({ demographics: value }),
  getAllEnrollments: (value) => ({ enrollments: value }),
  getEnrollment: (value) => ({ enrollment: value }),
  getAllGradingPeriods: (value) => ({ academicSessions: value }),
  getGradingPeriod: (value) => ({ academicSession: value }),
  getAllOrgs: (value) => ({ orgs: value }),
  getOrg: (value) => ({ org: value }),
  getAllSchools: (value) => ({ orgs: value }),
  getClassesForSchool: (value) => ({ classes: value }),
  getEnrollmentsForClassInSchool: (value) => ({ enrollments: value }),
  getStudentsForClassInSchool: (value) => ({ users: value }),
  getTeachersForClassInSchool: (value) => ({ users: value }),
  getCoursesForSchool: (value) => ({ courses: value }),
  getEnrollmentsForSchool: (value) => ({ enrollments: value }),
  getStudentsForSchool: (value) => ({ users: value }),
  getTeachersForSchool: (value) => ({ users: value }),
  getTermsForSchool: (value) => ({ academicSessions: value }),
  getSchool: (value) => ({ org: value }),
  getAllStudents: (value) => ({ users: value }),
  getStudent: (value) => ({ user: value }),
  getClassesForStudent: (value) => ({ classes: value }),
  getAllTeachers: (value) => ({ users: value }),
  getTeacher: (value) => ({ user: value }),
  getClassesForTeacher: (value) => ({ classes: value }),
  getAllTerms: (value) => ({ academicSessions: value }),
  getTerm: (value) => ({ academicSession: value }),
  getClassesForTerm: (value) => ({ classes: value }),
  getGradingPeriodsForTerm: (value) => ({ academicSessions: value }),
  getAllUsers: (value) => ({ users: value }),
  getUser: (value) => ({ user: value }),
  getClassesForUser: (value) => ({ classes: value }),
  getAllAssessmentLineItems: (value) => ({ assessmentLineItems: value }),
  getAssessmentLineItem: (value) => ({ assessmentLineItem: value }),
  getAllAssessmentResults: (value) => ({ assessmentResults: value }),
  getAssessmentResult: (value) => ({ assessmentResult: value }),
  getAllCategories: (value) => ({ categories: value }),
  getCategory: (value) => ({ category: value }),
  getCategoriesForClass: (value) => ({ categories: value }),
  getLineItemsForClass: (value) => ({ lineItems: value }),
  getResultsForLineItemForClass: (value) => ({ results: value }),
  getResultsForClass: (value) => ({ results: value }),
  getScoreScalesForClass: (value) => ({ scoreScales: value }),
  getResultsForStudentForClass: (value) => ({ results: value }),
  getAllLineItems: (value) => ({ lineItems: value }),
  getLineItem: (value) => ({ lineItem: value }),
  getAllResults: (value) => ({ results: value }),
  getResult: (value) => ({ result: value }),
  getScoreScalesForSchool: (value) => ({ scoreScales: value }),
  getAllScoreScales: (value) => ({ scoreScales: value }),
  getScoreScale: (value) => ({ scoreScale: value }),
  getResourcesForClass: (value) => ({ resources: value }),
  getResourcesForCourse: (value) => ({ resources: value }),
  getAllResources: (value) => ({ resources: value }),
  getResource: (value) => ({ resource: value }),
  getResourcesForUser: (value) => ({ resources: value }),
};
